#
# Copyright 2013-2018 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.14.1"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - JHI_PROFILE=dev
    - JHI_RUN_APP=1
    - JHI_PROTRACTOR=0
    - JHI_ENTITY=sql
    # if JHI_LIB_BRANCH value is release, use the release from Maven
    - JHI_LIB_REPO=https://github.com/jhipster/jhipster.git
    - JHI_LIB_BRANCH=release
    # if JHI_GEN_BRANCH value is release, use the release from NPM
    - JHI_GEN_REPO=https://github.com/jhipster/generator-jhipster.git
    - JHI_GEN_BRANCH=master
    # specific config
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - JHI_E2E_HEADLESS=true
    - JHI_SCRIPTS=$HOME/generator-jhipster/test-integration/scripts
  matrix:
    - JHI_APP=vuejs-default JHI_PROTRACTOR=1
    - JHI_APP=vuejs-noi18n JHI_PROTRACTOR=1
    - JHI_APP=vuejs-fulli18n-es
    - JHI_APP=vuejs-gateway
    - JHI_APP=vuejs-gradle

#----------------------------------------------------------------------
# Install all tools and check configuration
#----------------------------------------------------------------------
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Update NPM
  - npm install -g npm
  - $TRAVIS_BUILD_DIR/test-integration/scripts/04-git-config.sh

#----------------------------------------------------------------------
# Install JHipster and generate project+entities
#----------------------------------------------------------------------
install:
  - $TRAVIS_BUILD_DIR/test-integration/scripts/10-install-jhipster-vuejs.sh
  - $JHI_SCRIPTS/11-generate-entities.sh
  - $TRAVIS_BUILD_DIR/test-integration/scripts/12-generate-project-vuejs.sh
  - $JHI_SCRIPTS/13-replace-version-generated-project.sh
  - $JHI_SCRIPTS/14-jhipster-info.sh

#----------------------------------------------------------------------
# Launch tests
#----------------------------------------------------------------------
script:
  - $JHI_SCRIPTS/20-docker-compose.sh
  - $JHI_SCRIPTS/21-tests-backend.sh
  - $JHI_SCRIPTS/22-tests-frontend.sh
  - $JHI_SCRIPTS/23-package.sh
  - $JHI_SCRIPTS/24-tests-e2e.sh

#----------------------------------------------------------------------
# Cache
#----------------------------------------------------------------------
before_cache:
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-framework/
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-dependencies/
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-parent/
