os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.12.0"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
env:
  global:
    - JHI_PROFILE=dev
    - JHI_RUN_APP=1
    - JHI_PROTRACTOR=0
    # if JHI_LIB_REPO value is release, use the release from Maven
    - JHI_LIB_REPO=https://github.com/jhipster/jhipster.git
    - JHI_LIB_BRANCH=release
    # if JHI_GEN_BRANCH value is release, use the release from NPM
    - JHI_GEN_REPO=https://github.com/jhipster/generator-jhipster.git
    - JHI_GEN_BRANCH=release
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - JHI_E2E_HEADLESS=true
    - JHI_SCRIPTS=$TRAVIS_BUILD_DIR/test-integration/scripts
  matrix:
    - JHI_APP=ngx-default JHI_PROFILE=prod JHI_PROTRACTOR=1
    - JHI_APP=ngx-psql-es-noi18n JHI_PROFILE=prod JHI_PROTRACTOR=1
    - JHI_APP=ngx-gradle-fr JHI_PROFILE=prod JHI_PROTRACTOR=1
    - JHI_APP=ngx-mariadb-oauth2-sass-infinispan JHI_PROTRACTOR=1
    - JHI_APP=ms-ngx-gateway-eureka
    - JHI_APP=ms-micro-eureka
    - JHI_APP=ngx-mongodb-kafka-cucumber

#----------------------------------------------------------------------
# Install all tools and check configuration
#----------------------------------------------------------------------
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Update NPM
  - npm install -g npm

#----------------------------------------------------------------------
# Install JHipster and generate project+entities
#----------------------------------------------------------------------
install:
  - $JHI_SCRIPTS/10-install-jhipster.sh
  - $JHI_SCRIPTS/11-generate-entities.sh
  - $JHI_SCRIPTS/12-generate-project.sh
  - $JHI_SCRIPTS/13-replace-version-generated-project.sh
#----------------------------------------------------------------------
# Launch tests
#----------------------------------------------------------------------
script:
  - $JHI_SCRIPTS/20-docker-compose.sh
  - $JHI_SCRIPTS/21-tests-backend.sh
  - $JHI_SCRIPTS/22-tests-frontend.sh
  - $JHI_SCRIPTS/23-package.sh
  - $JHI_SCRIPTS/24-tests-e2e.sh
  - $JHI_SCRIPTS/25-sonar-analyze.sh

#----------------------------------------------------------------------
# Cache
#----------------------------------------------------------------------
before_cache:
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-framework/
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-dependencies/
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-parent/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/479b810ad42c816679fb
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
