#
# Copyright 2013-2018 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    JHI_PROFILE: dev
    JHI_RUN_APP: 1
    JHI_PROTRACTOR: 0
    JHI_LIB_REPO: https://github.com/jhipster/jhipster.git
    JHI_LIB_BRANCH: release
    JHI_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
    JHI_GEN_BRANCH: release
    SPRING_OUTPUT_ANSI_ENABLED: NEVER
    SPRING_JPA_SHOW_SQL: false
    JHI_DISABLE_WEBPACK_LOGS: true
    JHI_E2E_HEADLESS: true
    JHI_SCRIPTS: $BUILD_REPOSITORY_LOCALPATH/test-integration/scripts

  strategy:
    matrix:
      react-default:
        JHI_APP: react-default
        JHI_PROFILE: prod
        JHI_PROTRACTOR: 1
      react-noi18n-es-ws-gradle-session:
        JHI_APP: react-noi18n-es-ws-gradle-session
        JHI_PROTRACTOR: 1
      ms-ngx-gateway-eureka-oauth2:
        JHI_APP: ms-ngx-gateway-eureka-oauth2
        JHI_PROTRACTOR: 1
      ms-ngx-gateway-consul:
        JHI_APP: ms-ngx-gateway-consul
      ms-ngx-gateway-uaa:
        JHI_APP: ms-ngx-gateway-uaa
      ms-micro-consul:
        JHI_APP: ms-micro-consul
      ngx-session-cassandra-fr:
        JHI_APP: ngx-session-cassandra-fr
      ngx-couchbase:
        JHI_APP: ngx-couchbase
        JHI_PROFILE: prod
      webflux-mongodb:
        JHI_APP: webflux-mongodb

  steps:
  #----------------------------------------------------------------------
  # Install all tools and check configuration
  #----------------------------------------------------------------------
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
    displayName: 'TOOLS: install Node.js'
  - script: |
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      sudo apt update
      sudo apt install google-chrome-stable
    displayName: 'TOOLS: install google-chrome-stable'
  - script: sudo npm install -g npm
    displayName: 'TOOLS: update NPM'
  - bash: $(JHI_SCRIPTS)/01-display-configuration.sh
    displayName: 'TOOLS: display configuration'
  # need to be deleted, as soon as JHipster Core 3.4.0+ is released
  # See https://github.com/jhipster/generator-jhipster/issues/8572
  - bash: $(JHI_SCRIPTS)/02-display-tools.sh
    displayName: 'TOOLS: display installed tools'
  - bash: $(JHI_SCRIPTS)/03-system.sh
    displayName: 'TOOLS: configure tools installed by the system'

  #----------------------------------------------------------------------
  # Install JHipster and generate project+entities
  #----------------------------------------------------------------------
  - bash: $(JHI_SCRIPTS)/10-install-jhipster.sh
    displayName: 'GENERATION: install JHipster'
  - bash: $(JHI_SCRIPTS)/11-generate-entities.sh
    displayName: 'GENERATION: entities'
  - bash: $(JHI_SCRIPTS)/12-generate-project.sh
    displayName: 'GENERATION: project'
  - bash: $(JHI_SCRIPTS)/13-replace-version-generated-project.sh
    displayName: 'GENERATION: replace version in generated project'
  # need to be uncommented, as soon as JHipster Core 3.4.0+ is released
  # See https://github.com/jhipster/generator-jhipster/issues/8572
  # - bash: $(JHI_SCRIPTS)/14-jhipster-info.sh
  #   displayName: 'GENERATION: jhipster info'

  #----------------------------------------------------------------------
  # Launch tests
  #----------------------------------------------------------------------
  - bash: $(JHI_SCRIPTS)/20-docker-compose.sh
    displayName: 'TESTS: Start docker-compose containers'
  - bash: $(JHI_SCRIPTS)/21-tests-backend.sh
    displayName: 'TESTS: backend'
  - bash: $(JHI_SCRIPTS)/22-tests-frontend.sh
    displayName: 'TESTS: frontend'
  - bash: $(JHI_SCRIPTS)/23-package.sh
    displayName: 'TESTS: packaging'
  - bash: $(JHI_SCRIPTS)/24-tests-e2e.sh
    displayName: 'TESTS: End-to-End'
