#
# Copyright 2013-2021 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
trigger:
  branches:
    exclude:
      - dependabot/npm_and_yarn/generators/*
      - dependabot/github_actions/*
jobs:
  - job: Test
    condition: not(contains(variables['System.PullRequest.SourceBranch'], 'dependabot'))
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      # if JHI_LIB_BRANCH value is release, use the release from Maven
      JHI_LIB_REPO: https://github.com/jhipster/jhipster-bom.git
      JHI_LIB_BRANCH: dependabot/maven/org.springframework.boot-spring-boot-dependencies-2.5.5
      # if JHI_GEN_BRANCH value is release, use the release from NPM
      JHI_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
      JHI_GEN_BRANCH: main
      JHI_SCRIPTS: $(Build.Repository.LocalPath)/test-integration/scripts

    strategy:
      matrix:
        ms-ngx-gateway-eureka-jwt:
          JHI_APP: ms-ngx-gateway-eureka-jwt
          JHI_ENTITY: sqllight
          JHI_PROFILE: prod
          JHI_E2E: 1
        ms-ngx-gateway-eureka-oauth2:
          JHI_APP: ms-ngx-gateway-eureka-oauth2
          JHI_ENTITY: sqllight
          JHI_PROFILE: prod
          JHI_E2E: 1
        ms-micro-eureka-jwt:
          JHI_APP: ms-micro-eureka-jwt
          JHI_ENTITY: micro
        ms-micro-eureka-infinispan:
          JHI_APP: ms-micro-eureka-infinispan
          JHI_ENTITY: micro
        ms-react-gateway-consul-jwt:
          JHI_APP: ms-react-gateway-consul-jwt
          JHI_ENTITY: sqllight
          JHI_PROFILE: prod
          JHI_E2E: 1
        ms-react-gateway-consul-oauth2:
          JHI_APP: ms-react-gateway-consul-oauth2
          JHI_ENTITY: sqllight
          JHI_PROFILE: prod
          JHI_E2E: 1
        jdl-default:
          JHI_APP: jdl-default
          JHI_ENTITY: jdl
          JHI_PROFILE: prod
          JHI_E2E: 1
          JHI_TESTCONTAINERS: 1
    steps:
      #----------------------------------------------------------------------
      # Set checkout path.
      # Yeoman uses the package name to calculate namespaces.
      # Otherwise the namespace will be the path instead of jhispter:*.
      #----------------------------------------------------------------------
      - checkout: self
        path: generator-jhipster
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - bash: $(JHI_SCRIPTS)/01-configure-azure.sh
        displayName: 'TOOLS: configure azure environment'
      - bash: $(JHI_SCRIPTS)/01-display-configuration.sh
        displayName: 'TOOLS: display configuration'
      - bash: $(JHI_SCRIPTS)/03-system.sh
        displayName: 'TOOLS: configure tools installed by the system'
      - bash: $(JHI_SCRIPTS)/04-git-config.sh
        displayName: 'TOOLS: configure git'
      - task: NodeTool@0
        inputs:
          versionSpec: '$(JHI_NODE_VERSION)'
        displayName: 'TOOLS: install Node.js'
      - script: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
        displayName: 'TOOLS: install google-chrome-stable'

      #----------------------------------------------------------------------
      # Install JHipster and generate project+entities
      #----------------------------------------------------------------------
      - bash: $(JHI_SCRIPTS)/10-install-jhipster.sh
        displayName: 'GENERATION: install JHipster'
      - bash: $(JHI_SCRIPTS)/11-generate-config.sh
        displayName: 'GENERATION: config'
      - bash: $(JHI_SCRIPTS)/12-generate-project.sh
        displayName: 'GENERATION: project'
      - bash: $(JHI_SCRIPTS)/13-replace-version-generated-project.sh
        displayName: 'GENERATION: replace version in generated project'
      - bash: $(JHI_SCRIPTS)/14-jhipster-info.sh
        displayName: 'GENERATION: jhipster info'

      #----------------------------------------------------------------------
      # Bugs fix
      #----------------------------------------------------------------------
      - bash: $(JHI_SCRIPTS)/20-no-memory-limit-elasticsearch.sh
        displayName: 'BUGS-FIX: no memory limit for Elasticsearch'

      #----------------------------------------------------------------------
      # Launch tests
      #----------------------------------------------------------------------
      - bash: $(JHI_SCRIPTS)/20-docker-compose-npm.sh
        displayName: 'TESTS: Start docker-compose containers'
      - bash: $(JHI_SCRIPTS)/21-tests-backend-npm.sh
        displayName: 'TESTS: backend'
      - bash: $(JHI_SCRIPTS)/22-tests-frontend-npm.sh
        displayName: 'TESTS: frontend'
      - bash: $(JHI_SCRIPTS)/23-package-npm.sh
        displayName: 'TESTS: packaging'
      - bash: $(JHI_SCRIPTS)/24-tests-e2e-npm.sh
        displayName: 'TESTS: End-to-End'
