version: '2'
services:
<%_ if (devDatabaseType == 'mysql') { _%>
    <%= baseName.toLowerCase() %>-dev-mysql:
        extends:
            file: dev.yml
            service: <%= baseName.toLowerCase() %>-dev-mysql

<%_ } _%>
<%_ if (devDatabaseType == 'postgresql') { _%>
    <%= baseName.toLowerCase() %>-dev-postgresql:
        extends:
            file: dev.yml
            service: <%= baseName.toLowerCase() %>-dev-postgresql

<%_ } _%>
<%_ if (devDatabaseType == 'mongodb') { _%>
    <%= baseName.toLowerCase() %>-dev-mongodb:
        extends:
            file: dev.yml
            service: <%= baseName.toLowerCase() %>-dev-mongodb

<%_ } _%>
    <%= baseName.toLowerCase() %>-dev-app:
        image: jhipster/<%= baseName.toLowerCase() %>
        <%_ if (devDatabaseType == 'mysql') { _%>
        depends_on:
            - <%= baseName.toLowerCase() %>-dev-mysql
        links:
            - "<%= baseName.toLowerCase() %>-dev-mysql:mysql"
        <%_ } _%>
        <%_ if (devDatabaseType == 'postgresql') { _%>
        depends_on:
            - <%= baseName.toLowerCase() %>-dev-postgresql
        links:
            - "<%= baseName.toLowerCase() %>-dev-postgresql:postgresql"
        <%_ } _%>
        <%_ if (devDatabaseType == 'mongodb') { _%>
        depends_on:
            - <%= baseName.toLowerCase() %>-dev-mongodb
        links:
            - "<%= baseName.toLowerCase() %>-dev-mongodb:mongodb"
        <%_ } _%>
        external_links:
            - "jhipster-registry:registry"
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            <%_ if (applicationType == 'microservice' || applicationType == 'gateway') { _%>
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            <%_ } _%>
            <%_ if (devDatabaseType == 'mysql') { _%>
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/<%= baseName.toLowerCase() %>?useUnicode=true&characterEncoding=utf8&useSSL=false
            <%_ } _%>
            <%_ if (devDatabaseType == 'postgresql') { _%>
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/<%= baseName %>
            <%_ } _%>
            <%_ if (devDatabaseType == 'mongodb') { _%>
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=<%= baseName %>
            <%_ } _%>
        <%_ if (applicationType == 'gateway') { _%>
        ports:
            - "8080:8080"
        <%_ } _%>
        <%_ if (applicationType == 'microservice') { _%>
        expose:
            - "8081"
        <%_ } _%>
