version: '2'
services:
    <%=baseName.toLowerCase()%>-cassandra-migration:
        container_name: <%=baseName.toLowerCase()%>-cassandra-migration
        environment:
            - CASSANDRA_CONTACT_POINT=<%=baseName.toLowerCase()%>-cassandra
            - USER=docker-cassandra-migration
            # - DEBUG_LOG=1 # uncomment to show debug logs during the migration process
        build:
            context: .
            dockerfile: cassandra/Cassandra-Migration.Dockerfile
        volumes:
            - ../resources/config/cql:/cql:ro
