version: '2'
services:
    <%= baseName.toLowerCase() %>-elasticsearch:
        image: <%= DOCKER_ELASTICSEARCH %>
        # volumes:
        #     - ~/volumes/jhipster/<%= baseName %>/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
