version: '2'
services:
    <%= baseName.toLowerCase() %>-mongodb:
        container_name: <%= baseName.toLowerCase() %>-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/<%= baseName %>/mongodb/:/data/db/
