version: '2'
services:
    <%= baseName.toLowerCase() %>-mongodb:
        container_name: <%= baseName.toLowerCase() %>-mongodb
        image: <%= DOCKER_MONGODB %>
        ports:
            - "27017:27017"
        command: mongos --configdb <%= baseName.toLowerCase() %>-mongodb-config
    <%= baseName.toLowerCase() %>-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    <%= baseName.toLowerCase() %>-mongodb-config:
        image: <%= DOCKER_MONGODB %>
        container_name: <%= baseName.toLowerCase() %>-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
