version: '2'
services:
    <%= baseName.toLowerCase() %>-mysql:
        container_name: <%= baseName.toLowerCase() %>-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/<%= baseName %>/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=<%=baseName.toLowerCase()%>
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
