version: '2'
services:
    <%= baseName.toLowerCase() %>-postgresql:
        image: <%= DOCKER_POSTGRESQL %>
        # volumes:
        #     - ~/volumes/jhipster/<%= baseName %>/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=<%= baseName %>
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
