[libraries]
# caffeine
typesafe = { module = 'com.typesafe:config', version = '1.4.3' }

# hazelcast
hazelcast-hibernate53 = { module = 'com.hazelcast:hazelcast-hibernate53', version = '5.1.0' }

hazelcast-spring = { module = 'com.hazelcast:hazelcast-spring', version = '5.3.7' }

# memcached
xmemcached-provider = { module = 'com.google.code.simple-spring-memcached:xmemcached-provider', version = '4.1.3' }

xmemcached = { module = 'com.googlecode.xmemcached:xmemcached', version = '2.4.8' }

redisson = { module = 'org.redisson:redisson', version = '3.27.2' }
