version: '2'
services:
    elk-elasticsearch:
        image: elasticsearch:2.3.1
        ports:
            - 9200:9200
            - 9300:9300
    elk-logstash:
        image: logstash:2.3.0-1
        volumes:
            - ./log-monitoring/log-config/:/config-dir
        command: logstash -f /config-dir/logstash.conf
        ports:
            - 5000:5000/udp
    jhipster-console:
        image: jhipster/jhipster-console:v1.2.0
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_URL=http://elk-elasticsearch:9200
