[plugins]
gradle-git-properties = { id = 'com.gorylenko.gradle-git-properties', version = '2.4.1' }

node-gradle = { id = 'com.github.node-gradle.node', version = '7.0.0' }

gradle-liquibase = { id = 'org.liquibase.gradle', version = '2.2.0' }

gradle-sonarqube = { id = 'org.sonarqube', version = '4.3.1.3277' }

spotless-gradle-plugin = { id = 'com.diffplug.spotless', version = '6.21.0' }

gradle-modernizer-plugin = { id = 'com.github.andygoossens.gradle-modernizer-plugin', version = '1.8.0' }

gradle-enterprise = { id = 'com.gradle.enterprise', version = '3.14.1' }

common-custom-user-data-gradle-plugin = { id = 'com.gradle.common-custom-user-data-gradle-plugin', version = '1.11.1' }

gatling-gradle = { id = 'io.gatling.gradle', version = '3.9.5.5' }
