[libraries]
spring-cloud-dependencies = { module = 'org.springframework.cloud:spring-cloud-dependencies', version = '2025.0.0' }

springdoc = { module = 'org.springdoc:springdoc-openapi-starter-webmvc-api', version = '2.8.9' }

feign-reactor-bom = { module = 'com.playtika.reactivefeign:feign-reactor-bom', version = '4.2.1' }

cucumber-bom = { module = 'io.cucumber:cucumber-bom', version = '7.30.0' }

mongock-bom = { module = 'io.mongock:mongock-bom', version = '5.5.1' }

neo4j-migrations-spring-boot-starter = { module = 'eu.michael-simons.neo4j:neo4j-migrations-spring-boot-starter', version = '2.19.2' }

# Cassandra
lz4-java = { module = 'org.lz4:lz4-java', version = '1.8.0' }

# Couchbase
couchmove = { module = 'com.github.differentway:couchmove', version = '3.4.1' }

# jib
jib-maven-plugin = { module = 'com.google.cloud.tools:jib-maven-plugin', version = '3.4.6' }
jib-spring-boot-extension-maven = { module = 'com.google.cloud.tools:jib-spring-boot-extension-maven', version = '0.1.0' }

[plugins]
gradle-git-properties = { id = 'com.gorylenko.gradle-git-properties', version = '2.5.3' }

node-gradle = { id = 'com.github.node-gradle.node', version = '7.1.0' }

gradle-liquibase = { id = 'org.liquibase.gradle', version = '3.0.2' }

gradle-sonarqube = { id = 'org.sonarqube', version = '7.0.0.6105' }

spotless-gradle-plugin = { id = 'com.diffplug.spotless', version = '8.0.0' }

gradle-modernizer-plugin = { id = 'com.github.andygoossens.gradle-modernizer-plugin', version = '1.12.0' }

gradle-develocity = { id = 'com.gradle.develocity', version = '4.2.2' }

common-custom-user-data-gradle-plugin = { id = 'com.gradle.common-custom-user-data-gradle-plugin', version = '2.4.0' }

gatling-gradle = { id = 'io.gatling.gradle', version = '3.14.6.4' }

gradle-openapi-generator = { id = 'org.openapi.generator', version = '7.16.0' }

gradle-jib = { id = "com.google.cloud.tools.jib", version = "3.4.5" }
