[libraries]
spring-cloud-dependencies = { module = 'org.springframework.cloud:spring-cloud-dependencies', version = '2024.0.1' }

springdoc = { module = 'org.springdoc:springdoc-openapi-starter-webmvc-api', version = '2.8.9' }

feign-reactor-bom = { module = 'com.playtika.reactivefeign:feign-reactor-bom', version = '4.2.1' }

# Cucumber
testng = { module = 'org.testng:testng', version = '7.11.0' }
cucumber-bom = { module = 'io.cucumber:cucumber-bom', version = '7.23.0' }

mongock-bom = { module = 'io.mongock:mongock-bom', version = '5.5.1' }

neo4j-migrations-spring-boot-starter = { module = 'eu.michael-simons.neo4j:neo4j-migrations-spring-boot-starter', version = '2.18.1' }

# Cassandra
lz4-java = { module = 'org.lz4:lz4-java', version = '1.8.0' }

# Couchbase
couchmove = { module = 'com.github.differentway:couchmove', version = '3.4.1' }

# jib
jib-maven-plugin = { module = 'com.google.cloud.tools:jib-maven-plugin', version = '3.4.5' }
jib-spring-boot-extension-maven = { module = 'com.google.cloud.tools:jib-spring-boot-extension-maven', version = '0.1.0' }

[plugins]
gradle-git-properties = { id = 'com.gorylenko.gradle-git-properties', version = '2.5.2' }

node-gradle = { id = 'com.github.node-gradle.node', version = '7.1.0' }

gradle-liquibase = { id = 'org.liquibase.gradle', version = '3.0.2' }

gradle-sonarqube = { id = 'org.sonarqube', version = '6.2.0.5505' }

spotless-gradle-plugin = { id = 'com.diffplug.spotless', version = '7.1.0' }

gradle-modernizer-plugin = { id = 'com.github.andygoossens.gradle-modernizer-plugin', version = '1.11.0' }

gradle-develocity = { id = 'com.gradle.develocity', version = '4.1' }

common-custom-user-data-gradle-plugin = { id = 'com.gradle.common-custom-user-data-gradle-plugin', version = '2.3' }

gatling-gradle = { id = 'io.gatling.gradle', version = '3.14.3.2' }

gradle-openapi-generator = { id = 'org.openapi.generator', version = '7.14.0' }
