[plugins]
gradle-git-properties = { id = 'com.gorylenko.gradle-git-properties', version = '2.4.1' }

node-gradle = { id = 'com.github.node-gradle.node', version = '3.5.1' }

gradle-liquibase = { id = 'org.liquibase.gradle', version = '2.2.0' }

gradle-sonarqube = { id = 'org.sonarqube', version = '4.0.0.2929' }

gradle-modernizer-plugin = { id = 'com.github.andygoossens.gradle-modernizer-plugin', version = '1.7.0' }

gradle-enterprise = { id = 'com.gradle.enterprise', version = '3.12.6' }

common-custom-user-data-gradle-plugin = { id = 'com.gradle.common-custom-user-data-gradle-plugin', version = '1.10' }

gatling-gradle = { id = 'io.gatling.gradle', version = '3.9.3' }
