# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
<%_ if (applicationType != 'gateway') { _%>
    instance:
        hostname: <%= herokuAppName %>.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
<%_ } _%>
    client:
        serviceUrl:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
<%_ if (prodDatabaseType === 'postgresql' || prodDatabaseType === 'mysql' || prodDatabaseType === 'mariadb') { _%>
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        maximumPoolSize: 10
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
<%_ } else if (prodDatabaseType === 'mongodb') { _%>
    data:
        mongodb:
            uri: ${MONGODB_URI}?authMode=scram-sha1
<%_ } _%>
