#common configuration shared between all applications
configserver:
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml
jhipster:
    security:
        authentication:
            jwt:
                secret: <%= jwtSecretKey %>
<%_ if (useElk) { _%>
    logging:
        logstash: # forward logs to ELK
            enabled: true
            host: elk-logstash
    metrics:
        logs: # report metrics in the logs
            enabled: true
            reportFrequency: 60 # in seconds
<%_ } _%>
