#
# Copyright 2013-2020 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: npm@7 dependencies test
on:
    pull_request:
        paths:
            - 'generators/client/templates/angular/package.json'
    # Create a daily generic npm cache for frontends
    schedule:
        - cron: '0 0 * * *'
jobs:
    frontend:
        runs-on: ubuntu-20.04
        timeout-minutes: 10
        strategy:
            matrix:
                frontend: [angular]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.2
              with:
                  node-version: 15
            - run: npm --version
            - name: 'SETUP: Get date'
              id: get-date
              run: |
                  echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
            - name: 'SETUP: load npm cache'
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ matrix.frontend }}-${{ steps.get-date.outputs.date }}
            - name: 'Test Angular dependencies'
              if: matrix.frontend == 'angular'
              run: >-
                  npm install
                  @angular/common
                  @angular/compiler
                  @angular/forms
                  @angular/localize
                  @angular/platform-browser
                  @angular/platform-browser-dynamic
                  @angular/router
                  @angular/compiler-cli
                  @ngtools/webpack
              working-directory: ${{ github.workspace }}/generators/client/templates/${{ matrix.frontend }}
